services:
  - type: web
    name: cvpr-paper-search
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.api:app
    healthCheckPath: /
